Repository Podiihq/nailinda, pull requests merged in 2019-03, with the labels that each got.

#41 Delete patient
  config/dev.exs
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/patient/index.html.eex
  lib/nailinda_web/templates/patient/show.html.eex
  test/nailinda/user/user_test.exs
Labels: review

#50 add patients tests
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/router.ex
  test/nailinda/user/user_test.exs
Labels: in progress, patient

#21 circle-ci
  .circleci/config.yml
Labels: review

#40 Create doctor
  Dockerfile
  docker-compose.yml
  lib/nailinda/user/doctor.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/doctor_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/doctor/new.html.eex
  lib/nailinda_web/templates/patient/new.html.eex
  lib/nailinda_web/views/doctor_view.ex
  mix.lock
  priv/repo/migrations/20190204130625_doctor.exs
  test/nailinda/user/user_test.exs
Labels: review

#54 creating receptionist
  config/dev.exs
  lib/nailinda/user/receptionist.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/receptionist_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/receptionist/new.html.eex
  lib/nailinda_web/views/receptionist_view.ex
  priv/repo/migrations/20190308120316_create_receptionist.exs
  test/nailinda/user/user_test.exs
Labels: ready-for-review, receptionist

#55 set the project for heroku deployment
  .travis.yml
  Procfile
  compile
  config/prod.exs
  elixir_buildpack.config
  lib/nailinda_web/endpoint.ex
  phoenix_static_buildpack.config
Labels: review

#75 fixing dockerfile
  Dockerfile
Labels: review

#72 List of doctors
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/doctor_controller.ex
  lib/nailinda_web/templates/doctor/index.html.eex
  lib/nailinda_web/templates/doctor/show.html.eex
  test/nailinda_web/controllers/doctor_controller_test.exs
Labels: review

#71 Add a map
  .gitignore
  assets/css/app.css
  assets/js/app.js
  config/dev.exs
  lib/nailinda/user/patient.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/templates/layout/app.html.eex
  lib/nailinda_web/templates/patient/edit.html.eex
  lib/nailinda_web/templates/patient/index.html.eex
  lib/nailinda_web/templates/patient/new.html.eex
  lib/nailinda_web/templates/patient/show.html.eex
  lib/nailinda_web/views/patient_view.ex
  priv/repo/migrations/20190211125317_remove-location-column.exs
  priv/repo/migrations/20190312125227_addlocationcolumn.exs
Labels: review

#77 Show by id and list of receptionist
  lib/nailinda/user/patient.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/doctor_controller.ex
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/controllers/receptionist_controller.ex
  lib/nailinda_web/templates/doctor/edit.html.eex
  lib/nailinda_web/templates/doctor/form.html.eex
  lib/nailinda_web/templates/doctor/index.html.eex
  lib/nailinda_web/templates/doctor/new.html.eex
  lib/nailinda_web/templates/doctor/show.html.eex
  lib/nailinda_web/templates/receptionist/index.html.eex
  lib/nailinda_web/templates/receptionist/show.html.eex
  lib/nailinda_web/views/patient_view.ex
  priv/repo/migrations/20190211125317_remove-location-column.exs
  priv/repo/migrations/20190312125227_addlocationcolumn.exs
Labels: review

#80 run lints using make file
  .credo.exs
  .travis.yml
  Makefile
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/doctor_controller.ex
  priv/scripts/check_lint.sh
  test/nailinda/user/user_test.exs
  test/support/channel_case.ex
  test/support/conn_case.ex
  test/support/data_case.ex
  test/support/integration_case.ex
Labels: review

#81 Hospital
  lib/nailinda/facilities/facilities.ex
  lib/nailinda/facilities/hospital.ex
  lib/nailinda_web/controllers/hospital_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/hospital/edit.html.eex
  lib/nailinda_web/templates/hospital/index.html.eex
  lib/nailinda_web/templates/hospital/new.html.eex
  lib/nailinda_web/templates/hospital/show.html.eex
  lib/nailinda_web/views/hospital_view.ex
  priv/repo/migrations/20190315131657_create-hospitals.exs
  test/nailinda/facilities/hospital_test.exs
Labels: review

#83 User signup
  config/config.exs
  config/test.exs
  lib/nailinda/accounts.ex
  lib/nailinda/accounts/user.ex
  lib/nailinda/sessions.ex
  lib/nailinda/sessions/session.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/auth/token.ex
  lib/nailinda_web/auth/utils.ex
  lib/nailinda_web/controllers/authorize.ex
  lib/nailinda_web/controllers/session_controller.ex
  lib/nailinda_web/controllers/user_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/layout/app.html.eex
  lib/nailinda_web/templates/page/index.html.eex
  lib/nailinda_web/templates/session/new.html.eex
  lib/nailinda_web/templates/user/edit.html.eex
  lib/nailinda_web/templates/user/form.html.eex
  lib/nailinda_web/templates/user/index.html.eex
  lib/nailinda_web/templates/user/new.html.eex
  lib/nailinda_web/templates/user/show.html.eex
  lib/nailinda_web/views/layout_view.ex
  lib/nailinda_web/views/session_view.ex
  lib/nailinda_web/views/user_view.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20190314124631_create_users.exs
  priv/repo/migrations/20190314124633_create_sessions.exs
  test/nailinda/accounts/accounts_test.exs
  test/nailinda/sessions/sessions_test.exs
  test/nailinda_web/controllers/doctor_controller_test.exs
  test/nailinda_web/controllers/session_controller_test.exs
  test/nailinda_web/controllers/user_controller_test.exs
  test/support/auth_case.ex
Labels: review

#85 Install bulma
  assets/package.json
Labels: review

#88 use map to get coordinates of the location
  assets/package-lock.json
  lib/nailinda_web/templates/hospital/new.html.eex
Labels: review

#90 Title
  lib/nailinda_web/templates/layout/app.html.eex
Labels: review

#79 remove receptionist table
  lib/nailinda/user/receptionist.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/receptionist_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/receptionist/new.html.eex
  lib/nailinda_web/views/receptionist_view.ex
  priv/repo/migrations/20190308120316_create_receptionist.exs
  test/nailinda/user/user_test.exs
Labels: review

#92 show member only when showing hospitals
  lib/nailinda_web/templates/hospital/index.html.eex
  lib/nailinda_web/templates/hospital/show.html.eex
  lib/nailinda_web/views/hospital_view.ex
Labels: review

#91 Home
  assets/css/app.scss
  assets/css/phoenix.css
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
  assets/webpack.config.js
  lib/nailinda_web/templates/layout/app.html.eex
Labels: review

#102 pull request template
  docs/pull_request_template.md
Labels: dev, review

#99 add links to various sections of page
  lib/nailinda_web/templates/layout/app.html.eex
  lib/nailinda_web/templates/layout/navbar.html.eex
  lib/nailinda_web/templates/session/new.html.eex
Labels: UI, ready-for-review, review

#97 Redis location
  lib/nailinda/redis.ex
  lib/nailinda/user/user.ex
  mix.exs
  mix.lock
Labels: ready-for-review, review

#98 List patients location saved on redis
  lib/nailinda/redis.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/patient/index.html.eex
  lib/nailinda_web/templates/patient/locations.html.eex
  lib/nailinda_web/templates/patient/show.html.eex
  lib/nailinda_web/views/patient_view.ex
Labels: ready-for-review, review

#106 add full page landing page
  assets/css/app.scss
  assets/css/page/index.scss
  assets/static/images/bg.jpg
  assets/static/images/phoenix.png
  lib/nailinda_web/templates/layout/app.html.eex
  lib/nailinda_web/templates/page/index.html.eex
Labels: UI, ready-for-review, review

#109 User roles and cleanup
  lib/nailinda/accounts/accounts.ex
  lib/nailinda/accounts/doctor.ex
  lib/nailinda/accounts/patient.ex
  lib/nailinda/accounts/role.ex
  lib/nailinda/user/user.ex
  lib/nailinda_web/controllers/doctor_controller.ex
  lib/nailinda_web/controllers/patient_controller.ex
  lib/nailinda_web/controllers/role_controller.ex
  lib/nailinda_web/router.ex
  lib/nailinda_web/templates/role/new.html.eex
  lib/nailinda_web/views/patient_view.ex
  lib/nailinda_web/views/role_view.ex
  priv/repo/migrations/20190325113620_create_roles.exs
  test/nailinda/accounts/accounts_test.exs
  test/nailinda/facilities/hospital_test.exs
  test/nailinda/user/user_test.exs
  test/nailinda_web/controllers/doctor_controller_test.exs
Labels: review

#113 Site favicon logo
  assets/css/app.scss
  assets/css/customise_bulma.scss
  assets/static/favicon.ico
  assets/static/images/logo.png
  lib/nailinda_web/templates/layout/navbar.html.eex
  lib/nailinda_web/templates/session/new.html.eex
Labels: ready-for-review, review

#111 Reg details
  assets/css/app.css
  lib/nailinda_web/templates/hospital/new.html.eex
  lib/nailinda_web/templates/layout/app.html.eex
  lib/nailinda_web/templates/patient/new.html.eex
  lib/nailinda_web/views/error_helpers.ex
  mix.lock
Labels: ready-for-review, review

#115 add test to run on travis
  .travis.yml
  test/nailinda_web/controllers/page_controller_test.exs
Labels: review

#122 Create CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
Labels: ready-for-review, review

#119 Create LICENSE
  docs/LICENSE
Labels: ready-for-review, review
